#define FONT_SIZE_DEFAULT               24
#define FONT_SIZE_ATTACHMENT            30
#define FONT_SIZE_POPUP			30
#define FONT_SIZE_PREDICTIVE            40
#define FONT_SIZE_PREDICTIVE_COUNT      23
//#define FONT_COLOR                      0 192 255 255

#define MAIN_W				480 //ok
#define MAIN_H				800 //ok

#define COMPOSER_INDICATOR_H		48 //ok

#define COMPOSER_W 			MAIN_W
#define COMPOSER_H 			(MAIN_H-COMPOSER_INDICATOR_H)

#define COMPOSER_LIST_W         	460
#define COMPOSER_LIST_H         	85//80

#define DEFAULT_U_SPACE_H		16
#define ALL_LR_SPACE_W 			10
#define TEXT_LR_SPACE_W			18
#define TEXT_LR_SPACE_H			8

#define ACCOUNT_BUTTON_W 		440
#define ACCOUNT_BUTTON_H 		60
#define ACCOUNT_UD_SPACE_H 		((COMPOSER_LIST_H-ACCOUNT_BUTTON_H)/2)

#define SENDING_ACCOUNT_H		92
#define SENDING_ACCOUNT_UY		346
#define SENDING_ACCOUNT_DY		(SENDING_ACCOUNT_UY+SENDING_ACCOUNT_H)
#define SENDING_ACCOUNT_BUTTON_W	210
#define SENDING_ACCOUNT_BUTTON_H	60
#define SENDING_ACCOUNT_SPACE_W		10
#define SENDING_ACCOUNT_UD_SPACE_H	((SENDING_ACCOUNT_H-SENDING_ACCOUNT_BUTTON_H)/2)

#define PREDICTIVE_DN_L_X		28
#define PREDICTIVE_DN_R_X		406
#define PREDICTIVE_DN_D_Y		42
#define PREDICTIVE_EM_U_Y		46
#define PREDICTIVE_EM_D_Y		84
#define PREDICTIVE_EB_W			60
#define PREDICTIVE_EB_U_Y		5
#define PREDICTIVE_EB_D_Y		88
#define PREDICTIVE_CNT_D_Y		23


#define ATTACHMENT_LEFT_ICON_WH		80
#define ATTACHMENT_RIGHT_ICON_WH		80
#define ATTACHMENT_LEFT_ICON_U_Y	((COMPOSER_LIST_H-ATTACHMENT_LEFT_ICON_WH)/2)
#define ATTACHMENT_LEFT_ICON_D_Y        (ATTACHMENT_LEFT_ICON_WH+((COMPOSER_LIST_H-ATTACHMENT_LEFT_ICON_WH)/2))
#define ATTACHMENT_RIGHT_ICON_L_X	(COMPOSER_LIST_W-ATTACHMENT_RIGHT_ICON_WH-ALL_LR_SPACE_W)
#define ATTACHMENT_RIGHT_ICON_U_Y	((COMPOSER_LIST_H-ATTACHMENT_RIGHT_ICON_WH)/2)
#define ATTACHMENT_RIGHT_ICON_D_Y        (ATTACHMENT_RIGHT_ICON_WH+((COMPOSER_LIST_H-ATTACHMENT_RIGHT_ICON_WH)/2))
#define ATTACHMENT_FILENAME_W		150
#define ATTACHMENT_FILESIZE_W	 	120
#define ATTACHMENT_FILENAME_X		(ATTACHMENT_LEFT_ICON_WH+(2*ALL_LR_SPACE_W))
#define ATTACHMENT_FILESIZE_X		(ATTACHMENT_FILENAME_W+ATTACHMENT_LEFT_ICON_WH+(3*ALL_LR_SPACE_W))
#define ATTACHMENT_FILENAME_U_Y		((COMPOSER_LIST_H-FONT_SIZE_ATTACHMENT)/2)
#define ATTACHMENT_FILENAME_D_Y		(ATTACHMENT_FILENAME_U_Y+FONT_SIZE_ATTACHMENT)

#define ENTRY_TEXT_LR_SPACE_WH 		10
#define POPUP_UD_SPACE_H		30

//#define SOFTKEY_H			78

#define FONT_NAME                       "HelveN_Asia"
#define SIGN_FONT_NAME			"Sans:style=Oblique,HelveN_Asia"
//#define TEXT_CLASS_NAME                 "applications"
#define SLP_FONT_BOLD   	"SLP:style=Bold";
#define SLP_FONT_MEDIUM  	"SLP:style=Medium";
#define SLP_FONT_ROMAN   	"SLP:style=Roman";

