/*
 * =====================================================================================
 *
 *       Filename:  email-setting-define.h
 *
 *    Description:
 *
 *        Version:  1.0
 *        Created:  12/08/2009 02:17:00 PM
 *       Revision:  none
 *       Compiler:  gcc
 *
 *         Author:  Minju Kim
 *        Company:  my-company
 *
 * =====================================================================================
 */


#ifndef __EMAIL_SETTING_DEFINE_H_
#define __EMAIL_SETTING_DEFINE_H_

#define _KESSLER_

/* main size */
#ifdef _KESSLER_
#define MAIN_WIDTH 480
#define MAIN_HEIGHT 800
#endif

/* kessler theme */
#define S_INDICATOR_H		48	// no shadow for indicator
#define TITLEBAR_H		50	// including shadow
#define TITLEBAR_SHADOW_H	6
#define HEADER_H		78
#define HEADER_SHADOW_H	8

/* kessler offset */
#define INDI_TIT (S_INDICATOR_H+TITLEBAR_H-TITLEBAR_SHADOW_H)
#define INDI_HD (S_INDICATOR_H+HEADER_H-HEADER_SHADOW_H)

/* indicator */
#ifdef _KESSLER_
#define IND_H_R (52/MAIN_HEIGHT)
#else
#define IND_H_R (65/MAIN_HEIGHT)
#endif
#define IND_H_P (MAIN_HEIGHT * IND_H_R)
#define IND_SX_R 0.0
#define IND_EX_R 1.0
#define IND_SY_R 0.0
#define IND_EY_R IND_H_R

/* title */
#ifdef _KESSLER_
#define TIT_H_R (108/MAIN_HEIGHT)
#else
#define TIT_H_R (135/MAIN_HEIGHT)
#endif
#define TIT_H_P (MAIN_HEIGHT * TIT_H_R)
#define TIT_SX_R 0.0
#define TIT_EX_R 1.0
#define TIT_SY_R 0.0
#define TIT_EY_R TIT_H_R

/* Header */
#ifdef _KESSLER_
#define HD_H_R (108/MAIN_HEIGHT)
#else
#define HD_H_R (135/MAIN_HEIGHT)
#endif
#define HD_H_P (MAIN_HEIGHT * HD_H_R)
#define HD_SX_R 0.0
#define HD_EX_R 1.0
#define HD_SY_R (10.0/MAIN_HEIGHT)
#define HD_EY_R (HD_H_R+HD_SY_R)

/* softkey */
#ifdef _KESSLER_
#define SK_H_R (78/MAIN_HEIGHT)
#else
#define SK_H_R (98/MAIN_HEIGHT)
#endif
#define SK_H_P (MAIN_HEIGHT * SK_H_R)
#define SK_SX_R 0.0
#define SK_EX_R 1.0
#define SK_SY_R (1-SK_H_R)
#define SK_EY_R 1.0

/* swallow with title*/
#define SW_SX_R 0.0
#define SW_EX_R 1.0
#define SW_SY_R ((TIT_H_P-4)/MAIN_HEIGHT)
#define SW_EY_R 1.0

/* swallow with Header*/
#define SW_H_SX_R 0.0
#define SW_H_EX_R 1.0
#define SW_H_SY_R (HD_EY_R+16/MAIN_HEIGHT)
#define SW_H_EY_R 1.0

/* swallow with Header list*/
#define SW_HL_SX_R 0.0
#define SW_HL_EX_R 1.0
#define SW_HL_SY_R (HD_EY_R+2/MAIN_HEIGHT)
#define SW_HL_EY_R 1.0

/* preset account user info & server info */
#define USR_H_P 106
#define USR_H_H 412
#define USR_SX_R (16.0/480.0)
#define USR_EX_R (1-USR_SX_R)
#define USR_SY_R (USR_H_P/800.0)
#define USR_EY_R (USR_H_H /800.0)

#define SVR_H_P 420
#define SVR_H_H 726
#define SVR_SX_R USR_SX_R
#define SVR_EX_R (1-SVR_SX_R)
#define SVR_SY_R (SVR_H_P/800.0)
#define SVR_EY_R (SVR_H_H/800.0)

/* sending option */
#ifdef _KESSLER_
#define SDO_SX_R (8/MAIN_WIDTH)
#define SDO_SY_R (117/MAIN_HEIGHT)
#else
#define SDO_SX_R (16/MAIN_WIDTH)
#define SDO_SY_R (146/MAIN_HEIGHT)
#endif
#define SDO_EX_R (1-SDO_SX_R)
#define SDO_EY_R 1.0


#define TC_LIST_INDEX "tc_list_index"
#define TC_LIST_ITEM "tc_list_item"

/* theme.edc*/
#ifdef _KESSLER_
#define SUBJECT_H		92
#define SUBJECT_W		480
#define SUBJECT_TEXT1_START_X	18
#define SUBJECT_TEXT1_START_Y	8
#define SUBJECT_TEXT1_END_X		411
#define SUBJECT_TEXT1_END_Y		50
#define SUBJECT_TEXT2_START_X	18
#define SUBJECT_TEXT2_START_Y	50
#define SUBJECT_TEXT2_END_X		411
#define SUBJECT_TEXT2_END_Y		82

#define OPTION_H		102
#define OPTION_W		458
#define OPTION_TEXT1_START_X	18
#define OPTION_TEXT1_START_Y	8
#define OPTION_TEXT1_END_X		440
#define OPTION_TEXT1_END_Y		50
#define OPTION_TEXT2_START_X	18
#define OPTION_TEXT2_START_Y	52
#define OPTION_TEXT2_END_X		440
#define OPTION_TEXT2_END_Y		92

#define SINGLE_H		82
#define SINGLE_W		458
#define SINGLE_START_X	18
#define SINGLE_START_Y	8
#define SINGLE_END_X		440
#define SINGLE_END_Y		72

#define SINGLE_ICON_START_X	56
#define SINGLE_ICON_START_Y	8
#define SINGLE_ICON_END_X		440
#define SINGLE_ICON_END_Y		80
#define SINGLE_ICON_H		82

#define SINGLE_RIGHT_ICON_START_X		384
#define SINGLE_RIGHT_ICON_START_Y		8
#define SINGLE_RIGHT_ICON_END_X		480
#define SINGLE_RIGHT_ICON_END_Y		80

#define POPUP_H				80
#define POPUP_W				400
#define POPUP_START_X		25
#define POPUP_START_Y		8
#define POPUP_END_X		370
#define POPUP_END_Y		72
#define POPUP_ICON_X		340
#define POPUP_ICON_Y		12

#define SENDING_OPT_POPUP_TITLE_X_START 	(14/MAIN_WIDTH)
#define SENDING_OPT_POPUP_TITLE_Y_START 	(40/MAIN_HEIGHT)
#define SENDING_OPT_POPUP_TITLE_X_END 	(384/MAIN_WIDTH)
#define SENDING_OPT_POPUP_TITLE_Y_END 	(160/MAIN_HEIGHT)

#define SENDING_OPT_POPUP_LIST_X_START 	(10/MAIN_WIDTH)
#define SENDING_OPT_POPUP_LIST_Y_START 	(160/MAIN_HEIGHT)
#define SENDING_OPT_POPUP_LIST_X_END 	(470/MAIN_WIDTH)
#define SENDING_OPT_POPUP_LIST_Y_END 	(584/MAIN_HEIGHT)

#define SENDING_OPT_POPUP_OK_BTN_X_START 	(48/MAIN_WIDTH)
#define SENDING_OPT_POPUP_OK_BTN_Y_START 	(600/MAIN_HEIGHT)
#define SENDING_OPT_POPUP_OK_BTN_X_END 		(225/MAIN_WIDTH)
#define SENDING_OPT_POPUP_OK_BTN_Y_END 		(720/MAIN_HEIGHT)

#define SENDING_OPT_POPUP_CNL_BTN_X_START 	(254/MAIN_WIDTH)
#define SENDING_OPT_POPUP_CNL_BTN_Y_START 	(600/MAIN_HEIGHT)
#define SENDING_OPT_POPUP_CNL_BTN_X_END 	(432/MAIN_WIDTH)
#define SENDING_OPT_POPUP_CNL_BTN_Y_END 	(720/MAIN_HEIGHT)

#define BOX_LIST_PIC_OFFSET_X_REL1 -25
#define BOX_LIST_PIC_OFFSET_Y_REL1 -15
#define BOX_LIST_PIC_OFFSET_X_REL2	80
#define BOX_LIST_PIC_OFFSET_Y_REL2	86

#define COLOR1 255 255 255
#define COLOR2 153 153 153
#define COLOR3 0 0 0
#define COLOR4 128 128 128

#define SEND_PADDING_HEIGHT 500
#define SIGNATURE_SCROLLER 850

//account set up views
#define IME_HEIGHT 380
#define REDUCED_SCROLLER_HEIGHT (1 -IME_HEIGHT/MAIN_HEIGHT)
#define ICON_ACCOUNT_NAME_SX_R (14.0/480)
#define ICON_ACCOUNT_NAME_SY_R (52.0/800)
#define ICON_ACCOUNT_NAME_EX_R (66.0/480)
#define ICON_ACCOUNT_NAME_EY_R (104.0/800)

//#define ENTRY_BOX_HEIGHT 102
#define ENTRY_BOX_HEIGHT 112
#define ENTRY_BOX_WIDTH 470
#define ENTRY_MARGIN_LEFT_R 14/MAIN_WIDTH
#define ENTRY_HEADING_HEIGHT_R 40/ENTRY_BOX_HEIGHT
#define ENTRY_CONTENT_START_Y_R (1-ENTRY_HEADING_HEIGHT_R)
#define CHECKBOX_TEXT_WIDTH_R 320/ENTRY_BOX_WIDTH
#define CHECKBOX_ICON_START_X_R (CHECKBOX_TEXT_WIDTH_R)

#define SERVER_POPUP_SW_SX 7/480
#define SERVER_POPUP_SW_SY 16/800
#define SERVER_POPUP_SW_EX 472/480
#define SERVER_POPUP_SW_EY	520/800

#define SERVER_POPUP_LEFT_BTN_SX 48/480
#define SERVER_POPUP_LEFT_BTN_SY 528/800
#define SERVER_POPUP_LEFT_BTN_EX (SERVER_POPUP_LEFT_BTN_SX + 0.35)
#define SERVER_POPUP_LEFT_BTN_EY (SERVER_POPUP_LEFT_BTN_SY + 0.20)

#define SERVER_POPUP_RIGHT_BTN_SX (SERVER_POPUP_LEFT_BTN_SX + 0.45)
#define SERVER_POPUP_RIGHT_BTN_SY SERVER_POPUP_LEFT_BTN_SY
#define SERVER_POPUP_RIGHT_BTN_EX (SERVER_POPUP_LEFT_BTN_SX + 0.80)
#define SERVER_POPUP_RIGHT_BTN_EY SERVER_POPUP_LEFT_BTN_EY


#define CLICKED_COODS_DIFFERENCE 5
#define PADDING_HEIGHT 600
#define EMPTY_RECTANGLE 42
#define SEPARATOR_HEIGHT 8

#define BRING_IN_EMAIL_ADDRESS 44
#define BRING_IN_USER_NAME_Y (BRING_IN_EMAIL_ADDRESS + ENTRY_BOX_HEIGHT)
#define BRING_IN_PASSWORD_Y (BRING_IN_USER_NAME_Y + ENTRY_BOX_HEIGHT)

/*#define BRING_IN_OUTGOING_SERVER_Y 90
#define BRING_IN_INCOMING_PORTNO_Y (BRING_IN_OUTGOING_SERVER_Y + ENTRY_BOX_HEIGHT)
#define BRING_IN_OUTGOING_PORTNO_Y (BRING_IN_INCOMING_PORTNO_Y+ENTRY_BOX_HEIGHT)
#define BRING_IN_SENDING_USERNAME_Y (BRING_IN_OUTGOING_PORTNO_Y+ENTRY_BOX_HEIGHT)
#define BRING_IN_SENDING_PASSWORD_Y (BRING_IN_SENDING_USERNAME_Y+ENTRY_BOX_HEIGHT)*/

#define BRING_IN_INCOMING_SERVER_Y 44
#define BRING_IN_INCOMING_PORTNO_Y (BRING_IN_INCOMING_SERVER_Y + ENTRY_BOX_HEIGHT)
#define BRING_IN_INCOMING_SSL_Y (BRING_IN_INCOMING_PORTNO_Y + ENTRY_BOX_HEIGHT)
#define BRING_IN_OUTGOING_SERVER_Y (BRING_IN_INCOMING_PORTNO_Y + EMPTY_RECTANGLE + ENTRY_BOX_HEIGHT*3)
#define BRING_IN_OUTGOING_PORTNO_Y (BRING_IN_OUTGOING_SERVER_Y + ENTRY_BOX_HEIGHT)
#define BRING_IN_SENDING_SSL_Y (BRING_IN_OUTGOING_PORTNO_Y + ENTRY_BOX_HEIGHT)
#define BRING_IN_SENDING_USERNAME_Y (BRING_IN_SENDING_SSL_Y + ENTRY_BOX_HEIGHT*3)
#define BRING_IN_SENDING_PASSWORD_Y (BRING_IN_SENDING_USERNAME_Y + ENTRY_BOX_HEIGHT)

/*#define BRING_IN_EDIT_PASSWORD_Y 90
#define BRING_IN_EDIT_INCOMING_SERVER_Y (BRING_IN_EDIT_PASSWORD_Y + ENTRY_BOX_HEIGHT+ EMPTY_RECTANGLE)
#define BRING_IN_EDIT_OUTGOING_SERVER_Y (BRING_IN_EDIT_INCOMING_SERVER_Y + ENTRY_BOX_HEIGHT)
#define BRING_IN_EDIT_INCOMING_PORTNO_Y (BRING_IN_EDIT_OUTGOING_SERVER_Y + ENTRY_BOX_HEIGHT)
#define BRING_IN_EDIT_OUTGOING_PORTNO_Y (BRING_IN_EDIT_INCOMING_PORTNO_Y + ENTRY_BOX_HEIGHT)
#define BRING_IN_EDIT_SENDING_USERNAME_Y (BRING_IN_EDIT_OUTGOING_PORTNO_Y + ENTRY_BOX_HEIGHT)
#define BRING_IN_EDIT_SENDING_PASSWORD_Y (BRING_IN_EDIT_SENDING_USERNAME_Y + ENTRY_BOX_HEIGHT)*/

#define BRING_IN_EDIT_ACCOUNT_NAME_Y 0
#define BRING_IN_EDIT_EMAIL_ADDR_Y (BRING_IN_EDIT_ACCOUNT_NAME_Y+BRING_IN_EMAIL_ADDRESS)
#define BRING_IN_EDIT_USER_NAME_Y (BRING_IN_EDIT_EMAIL_ADDR_Y+ENTRY_BOX_HEIGHT)
#define BRING_IN_EDIT_PASSWORD_Y (BRING_IN_EDIT_USER_NAME_Y + ENTRY_BOX_HEIGHT)

#define BRING_IN_EDIT_INCOMING_SERVER_Y (BRING_IN_EDIT_PASSWORD_Y+ENTRY_BOX_HEIGHT)
#define BRING_IN_EDIT_INCOMING_PORT_Y (BRING_IN_EDIT_INCOMING_SERVER_Y+ENTRY_BOX_HEIGHT)
#define BRING_IN_EDIT_INCOMING_SSL_Y (BRING_IN_EDIT_INCOMING_PORT_Y+ENTRY_BOX_HEIGHT)

#define BRING_IN_EDIT_OUTGOING_SERVER_Y (BRING_IN_EDIT_INCOMING_SSL_Y+ENTRY_BOX_HEIGHT*3)
#define BRING_IN_EDIT_OUTGOING_PORT_Y (BRING_IN_EDIT_OUTGOING_SERVER_Y+ENTRY_BOX_HEIGHT)
#define BRING_IN_EDIT_OUTGOING_SSL_Y (BRING_IN_EDIT_OUTGOING_PORT_Y+ENTRY_BOX_HEIGHT)
#define BRING_IN_EDIT_SENDING_USERNAME_Y (BRING_IN_EDIT_OUTGOING_SSL_Y+ENTRY_BOX_HEIGHT*3)
#define BRING_IN_EDIT_SENDING_PASSWORD_Y (BRING_IN_EDIT_SENDING_USERNAME_Y+ENTRY_BOX_HEIGHT)

#define BRING_IN_EDIT
#define BRING_IN_EDIT


#endif

#endif /* __EMAIL_SETTING_DEFINE_H_ */





